name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build all targets
        run: make build

      - name: Create tar.gz archive
        run: tar -czf zfssnap-binaries.tar.gz -C bin .

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: zfssnap-binaries
          path: zfssnap-binaries.tar.gz
          if-no-files-found: error

